### ISSUE TITLE
Count cyclomatic complexity of _to_rgba_no_colorcycle@colors.py by hand

### ISSUE THREAD

**Issue by haval0** [filippaleuckfeld/matplotlib#6]
Two people need to check this for the function. Add to the report when finished

**Comment by haval0** [comment]
Getting only 18 on this one, despite lizard saying 36. Using the formula from the slides, M = pi - s + 2 = 29 - 13 + 2

**Comment by filippaleuckfeld** [comment]
function rewrites c to RGBA color, in the end of the function c should have length 3 or 4. 
We have two if statements that uses a for loop inside
`if not all(isinstance(x, Real) for x in c):`
and 
`if any(elem < 0 or elem > 1 for elem in c):`
and I guess that these if statements should be considered for each element in c? And since that is at most 4 this will evaluate to 4 each. 
Total will therefore be: `pi = 31` and `s = 14` so `M = pi - s + 2 = 31 - 13 + 2 = 20`

**Comment by filippaleuckfeld** [comment]
I have missed to count the for loops. Will add them now

**Comment by filippaleuckfeld** [comment]
It gets messy here since theres for loops inside the if statement? What should we do here? Maybe you should only count the if statement once and the for statement once?

**Comment by filippaleuckfeld** [comment]
Adding the four for loops found (the ones not in if statements) to the previous calc I get pi = 35 and s = 14

**Comment by filippaleuckfeld** [comment]
So we should not calculate for each if statement so therefore my final result is `pi = 29` and `s = 14`

**Comment by haval0** [comment]
I also got s = 14 after a recount!

**Comment by haval0** [comment]
I also get pi = somewhere between 34 and 36 after counting with the for loops.

Unsure whether this:
`if any(elem < 0 or elem > 1 for elem in c):`
counts as 2 or 3 ?

And unsure whether `if not (0 <= c <= 1):` counts as 1 or 2
